#####################################
# UPDATE APT CACHES, UPGRADE SYSTEM #
#####################################

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 604800 # One week in seconds
