#######################
# INITIAL SETUP TASKS #
#######################

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Set locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Disable SSH host hashing
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    search_string: "HashKnownHosts yes"
    line: "HashKnownHosts no"

- name: Add GitHub fingerprint to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

- name: Add Bitbucket fingerprint to known_hosts
  ansible.builtin.known_hosts:
    name: bitbucket.org
    key: bitbucket.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPIQmuzMBuKdWeF4+a2sjSSpBK0iqitSQ+5BM9KhpexuGt20JpTVM7u5BDZngncgrqDMbWdxMWWOGtZ9UgbqgZE=

- name: Configure git
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    create: true
    insertbefore: BOF
    marker: "# {mark} USER CONFIG BLOCK"
    block: |
      [user]
          name = VirtualWolf
          email = virtualwolf@virtualwolf.org

- name: Set SELECTED_EDITOR
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.selected_editor"
    content: "SELECTED_EDITOR=/usr/bin/vim.basic"

- name: Set SELECTED_EDITOR for root user
  become: true
  ansible.builtin.copy:
    dest: "/root/.selected_editor"
    content: "SELECTED_EDITOR=/usr/bin/vim.basic"


#####################################
# UPDATE APT CACHES, UPGRADE SYSTEM #
#####################################

- name: Update and upgrade apt packages
  ansible.builtin.include_role:
    name: upgrade_packages

- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-config-auto-update
      - vim
      - git
      - tmux
      - jq

# To see all the available update sources to use, run:
# sudo apt-cache policy | grep 'o=[^,]*.a=[^,]*'

# This is necessary for Buster on the Rasperry Pi Zero W
- name: Add Raspbian sources to unattended-upgrades list
  become: true
  ansible.builtin.copy:
    src: files/51add-raspbian-sources-to-unattended-upgrades
    dest: /etc/apt/apt.conf.d/
  when:
    - ansible_facts["distribution_major_version"] == "10"

- name: Add Docker to unattended-upgrades packages
  become: true
  ansible.builtin.copy:
    src: files/51add-docker-to-unattended-upgrades
    dest: /etc/apt/apt.conf.d/
  when:
    - inventory_hostname in groups.server

- name: Enable auto-reboot for unattended-upgrades
  become: true
  ansible.builtin.copy:
    src: files/51automatic-reboot-for-unattended-upgrades
    dest: /etc/apt/apt.conf.d/

- name: Enable unattended-upgrades cron job
  become: true
  ansible.builtin.cron:
    name: Schedule automatic upgrades
    minute: 0
    hour: 20
    user: root
    cron_file: unattended-upgrades
    job: /usr/bin/unattended-upgrade -d

- name: Add systemd unit for Pushover notifications on reboot
  become: true
  ansible.builtin.template:
    src: templates/pushover.service.j2
    dest: /usr/lib/systemd/system/pushover.service
    mode: '0400'
  register: pushover

- name: Enable Pushover systemd service
  become: true
  ansible.builtin.systemd:
    name: pushover
    enabled: true
    state: started
    daemon_reload: true


###########################
# CREATE SOURCE DIRECTORY #
###########################

- name: "Create {{ source_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ source_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


#################
# SET UP CONFIG #
#################

- name: Clone config repository
  ansible.builtin.include_role:
    name: update_config_repository_and_bashmarks
