#################
# SET UP CONFIG #
#################

- name: Clone config repository
  ansible.builtin.git:
    repo: git@bitbucket.org:VirtualWolf/config.git
    dest: "{{ source_dir }}/config"
  register: config_repository
  tags:
    - update-config

- name: Update SSH config file permissions after a repository update
  ansible.builtin.file:
    path: "{{ source_dir }}/config/ssh/config"
    mode: "600"
  when: config_repository.changed == true
  tags:
    - update-config

- name: Run user shell setup tasks
  ansible.builtin.include_role:
    name: config_initialisation


####################
# UPDATE BASHMARKS #
####################

- name: Configure default bashmarks bookmarks
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.sdirs"
    create: true
    marker: "# {mark} ANSIBLE MANAGED DEFAULT BASHMARKS"
    block: |
      export DIR_s="{{ source_dir }}"
      export DIR_config="{{ source_dir }}/config"
  tags:
    - update-bashmarks

- name: Configure dashboard bashmarks bookmarks
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.sdirs"
    create: true
    marker: "# {mark} ANSIBLE MANAGED DASHBOARD BASHMARKS"
    block: |
      export DIR_hbc="{{ source_dir }}/hyperpixel-brightness-control"
  when:
    - inventory_hostname in groups.dashboards
  tags:
    - update-bashmarks

- name: Configure e-ink dashboard bashmarks bookmarks
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.sdirs"
    create: true
    marker: "# {mark} ANSIBLE MANAGED E-INK DASHBOARD BASHMARKS"
    block: |
      export DIR_ptd="{{ source_dir }}/papirus-temperature-displayer"
  when:
    - inventory_hostname in groups.e_ink_dashboards
  tags:
    - update-bashmarks

- name: Configure server bashmarks bookmarks
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.sdirs"
    create: true
    marker: "# {mark} ANSIBLE MANAGED SERVER BASHMARKS"
    block: |
      export DIR_mosquitto="{{ source_dir }}/mosquitto/fourbee"
      export DIR_pvo="{{ source_dir }}/powerwall-to-pvoutput-uploader"
      export DIR_phd="{{ source_dir }}/pi-home-dashboard"
      export DIR_shairport="{{ source_dir }}/shairport-sync"
  when:
    - inventory_hostname in groups.server
  tags:
    - update-bashmarks
