####################
# JUSTBOOM DAC HAT #
####################

- name: Disable default audio configuration in config.txt for the JustBoom DAC HAT
  become: true
  ansible.builtin.lineinfile:
    path: "{{ boot_config_txt_path }}"
    line: dtparam=audio=on
    state: absent

- name: Enable JustBoom DAC HAT audio configuration and disable HDMI audio
  become: true
  ansible.builtin.blockinfile:
    path: "{{ boot_config_txt_path }}"
    block: |
      dtparam=audio=off
      dtoverlay=vc4-kms-v3d,noaudio
      dtoverlay=justboom-dac
    marker: "# {mark} ANSIBLE MANAGED JUSTBOOM CONFIGURATION"
  register: dac_overlay

- name: Reboot if the DAC HAT overlay has changed
  become: true
  ansible.builtin.reboot:
  when: dac_overlay.changed
  notify: Reboot system
