# Fourbee is always connected directly via ethernet
# and so has no need for wifi or Bluetooth to be on
- name: Disable wifi and Bluetooth for Fourbee
  become: true
  ansible.builtin.blockinfile:
    path: "{{ boot_config_txt_path }}"
    block: |
      dtoverlay=disable-wifi
      dtoverlay=disable-bt
    marker: "# {mark} ANSIBLE MANAGED WIRELESS CONFIGURATION"
  notify: Reboot system
  when:
    - inventory_hostname == 'fourbee'

- name: Install and configure Chrony
  ansible.builtin.import_tasks: chrony.yml
  tags:
    - chrony

- name: Configure audio for the JustBoom DAC HAT
  ansible.builtin.import_tasks: justboom_dac_hat.yml

- name: Build and install shairport-sync
  ansible.builtin.import_tasks: shairport-sync.yml
  tags:
    - shairport-sync

- name: Configure and start Mosquitto
  ansible.builtin.import_tasks: mosquitto.yml
  tags:
    - mosquitto

- name: Clone and start powerwall-to-pvoutput-uploader
  ansible.builtin.import_tasks: powerwall-to-pvoutput-uploader.yml
  tags:
    - pvoutput-uploader

- name: Clone and start pi-home-dashboard
  ansible.builtin.import_tasks: pi-home-dashboard.yml
  tags:
    - pi-home-dashboard
