#############
# MOSQUITTO #
#############

- name: Install Mosquitto
  become: true
  ansible.builtin.apt:
    pkg:
      - mosquitto
      - mosquitto-clients

- name: Add Mosquitto configuration
  become: true
  ansible.builtin.template:
    src: templates/mosquitto.conf.j2
    dest: /etc/mosquitto/conf.d/custom.conf
  notify: Restart Mosquitto
