##################################
# POWERWALL TO PVOUTPUT UPLOADER #
##################################

- name: Clone powerwall-to-pvoutput-uploader repository
  ansible.builtin.git:
    repo: "https://github.com/VirtualWolf/powerwall-to-pvoutput-uploader.git"
    dest: "{{ source_dir }}/powerwall-to-pvoutput-uploader"
  register: repository

- name: Add powerwall-to-pvoutput-uploader configuration
  ansible.builtin.template:
    src: templates/powerwall-to-pvoutput-uploader-config.j2
    dest: "{{ source_dir }}/powerwall-to-pvoutput-uploader/.env"
  register: config

- name: Start powerwall-to-pvoutput-uploader
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ source_dir }}/powerwall-to-pvoutput-uploader"
    build: "{{ 'always' if repository.changed else 'policy' }}"
    state: "{{ 'restarted' if config.changed else 'present' }}"
