#######################
# INITIAL SETUP TASKS #
#######################

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Set locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Disable SSH host hashing
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    search_string: "HashKnownHosts yes"
    line: "HashKnownHosts no"

- name: Configure git
  ansible.builtin.template:
    src: templates/git-config.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Add GitHub fingerprint to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=


#####################################################
# UPDATE APT CACHES, UPGRADE SYSTEM, SET UP UPDATES #
#####################################################

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 604800 # One week in seconds

- name: Install vim
  become: true
  ansible.builtin.apt:
    name: vim
