#######################
# INITIAL SETUP TASKS #
#######################

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Set locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Disable SSH host hashing
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    search_string: "HashKnownHosts yes"
    line: "HashKnownHosts no"

- name: Add GitHub fingerprint to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

- name: Add Bitbucket fingerprint to known_hosts
  ansible.builtin.known_hosts:
    name: bitbucket.org
    key: bitbucket.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPIQmuzMBuKdWeF4+a2sjSSpBK0iqitSQ+5BM9KhpexuGt20JpTVM7u5BDZngncgrqDMbWdxMWWOGtZ9UgbqgZE=

- name: SSH to Bitbucket to prompt for 1Password SSH access early on
  ansible.builtin.command: ssh -T git@bitbucket.org

- name: Configure git
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    create: true
    insertbefore: BOF
    block: |
      [user]
          name = VirtualWolf
          email = virtualwolf@virtualwolf.org


#####################################################
# UPDATE APT CACHES, UPGRADE SYSTEM, SET UP UPDATES #
#####################################################

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 604800 # One week in seconds

- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - vim
      - git
      - tmux


###########################
# CREATE SOURCE DIRECTORY #
###########################

- name: "Create {{ source_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ source_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Config repository setup
  ansible.builtin.import_tasks: config_repository.yml
