- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest

- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/raspbian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '644'

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: true

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: latest

- name: Install Docker module and PyYAML modules for Python
  become: true
  ansible.builtin.pip:
    name:
      - docker
      - pyyaml
      - docker-compose
