- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest

- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/raspbian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '644'

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: true

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: latest

- name: Enable live restore
  become: true
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/
  register: live_restore_enabled

- name: Reload Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: reloaded
  when: live_restore_enabled.changed
