ansible_ssh_extra_args: "-A"
ansible_user: pi
timezone: Australia/Sydney

git_name: VirtualWolf
git_email: virtualwolf@virtualwolf.org

nodejs_version: "18.17.1"

source_dir: /usr/local/src/pi

# Bookworm (Debian 12) moved /boot/config.txt to /boot/firmware/config.txt
boot_config_txt_path: |-
  {%- if ansible_facts['distribution_major_version'] | int >= 12 -%}
    /boot/firmware/config.txt
  {%- else -%}
    /boot/config.txt
  {%- endif -%}

mqtt_host: fourbee

mqtt_topics:
  outdoor:
    weather: home/outdoor/weather
    airquality: home/outdoor/airquality
  indoor:
    weather: home/indoor/weather
  office:
    weather: home/office/weather
  backroom:
    weather: home/backroom/weather
  power_usage: home/power
  display_commands: commands/displays
