#############
# MOSQUITTO #
#############

mosquitto_connection_name: "{{ lookup('community.general.onepassword', 'Mosquitto configuration', field='connection name') }}"
mosquitto_remote_connection_address: "{{ lookup('community.general.onepassword', 'Mosquitto configuration', field='remote address') }}"
mosquitto_remote_username: "{{ lookup('community.general.onepassword', 'Mosquitto configuration', field='username') }}"
mosquitto_remote_password: "{{ lookup('community.general.onepassword', 'Mosquitto configuration', field='password') }}"
mqtt_host: "{{ ansible_hostname }}"


##################################
# POWERWALL TO PVOUTPUT UPLOADER #
##################################

powerwall_to_pvoutput_uploader_postgres_password: "{{ lookup('community.general.onepassword', 'PVOutput', field='docker postgres password') }}"
powerwall_url: https://10.0.2.202
powerwall_email: "{{ lookup('community.general.onepassword', 'Powerwall', field='username') }}"
powerwall_password: "{{ lookup('community.general.onepassword', 'Powerwall', field='password') }}"
pvoutput_timezone: Australia/Sydney
pvoutput_api_key: "{{ lookup('community.general.onepassword', 'PVOutput', field='api key') }}"
pvoutput_system_id: "{{ lookup('community.general.onepassword', 'PVOutput', field='system id') }}"


#####################
# PI HOME DASHBOARD #
#####################

pi_home_dashboard_latitude: -33.872761
pi_home_dashboard_longitude: 151.205338
esp32_client_ids:
  - outdoor
  - outdoor-airquality
  - backroom
  - indoor
  - office
  - indoor-aq-status
  - office-aq-status

############################
# SHAIRPORT SYNC AND NQPTP #
############################

shairport_sync_version: "4.3.4"
nqptp_version: "1.2.4"
